// Every agent shown on the site. Media lives at media/<id>.mp4 + media/<id>.jpg.
// The first FEATURED_COUNT are the headline showcase (bottom rail); the rest sit behind "+ more agents".
// To add an agent: drop the two media files in, add one entry here. Nothing else changes.
window.FEATURED_COUNT = 9;

window.AGENTS = [
  { id: 'roof', short: 'Roof', name: 'Roof Opportunity Agent', tag: 'Storms, spotted!',
    blurb: 'For roofing companies — turns every hail storm into booked inspections.',
    steps: ['Monitors hail & storm reports', 'Pulls aerial imagery', 'Detects visible roof damage', 'Verifies the property owner', 'Renders an inspection video', 'Mails postcard · updates CRM'] },
  { id: 'catalog', short: 'Catalog', name: 'Catalog-to-Cinematic Agent', tag: 'Catalogs, filmed!',
    blurb: 'For content studios — turns a Shopify catalog into a product film and a live landing page.',
    steps: ['Finds Shopify stores', 'Pulls the live product catalog', 'Rebuilds product in cinematic scenes', 'Renders a 15-second film', 'Builds a Shop-Now landing page', 'Sends it to the store owner'] },
  { id: 'skincare', short: 'Skincare', name: 'Skincare Campaign Agent', tag: 'Products, animated!',
    blurb: 'For beauty marketers — a complete, brand-ready creative kit in minutes.',
    steps: ['Scans skincare brand catalogs', 'Picks the hero product', 'Collects official images', 'Renders an application reel', 'Builds matching ad creatives', 'Delivers a brand-ready kit'] },
  { id: 'reelbnb', short: 'ReelBnB', name: 'ReelBnB AI', tag: 'Listings, upgraded!',
    blurb: 'For short-stay marketers — finds 5-star hosts with weak photos and mails them a cinematic ad.',
    steps: ['Scrapes 5-star hidden-gem listings', 'Skips pro-managed properties', 'Checks photo quality with vision', 'Pairs guest reviews with rooms', 'Renders a 9:16 cinematic ad', 'Mails the host a QR postcard'] },
  { id: 'vanwrap', short: 'VanWrap', name: 'Van WrapScout AI', tag: 'Vans, wrapped!',
    blurb: 'For wrap shops — shows new contractors their own van, already wrapped.',
    steps: ['Scans new contractor licences', 'Matches their Google profile', 'Pulls their real van photo', 'Renders a custom vinyl wrap', 'Builds a QR preview page', 'Prints & mails the postcard'] },
  { id: 'restaurant', short: 'Restaurant', name: 'Restaurant Launch Kit Agent', tag: 'Openings, launched!',
    blurb: 'For agencies — reaches new restaurants before they open, launch kit in hand.',
    steps: ['Watches new restaurant licences', 'Matches permits & records', 'Filters out chains', 'Identifies cuisine & owner', 'Generates a launch reel', 'Ships the creative kit'] },
  { id: 'storefront', short: 'Storefront', name: 'Storefront Sign Agent', tag: 'Signs, imagined!',
    blurb: 'For sign makers — renders the tenant’s sign on their real building before opening day.',
    steps: ['Pulls new commercial permits', 'Extracts the incoming tenant', 'Finds the real storefront photo', 'Renders their sign on the building', 'Cuts a before/after video', 'Mails it before opening day'] },
  { id: 'webpost', short: 'WebPost', name: 'WebPost AI', tag: 'Websites, mailed!',
    blurb: 'For web designers — builds the site first, then mails the owner a postcard of it.',
    steps: ['Scrapes local businesses', 'Builds each one a website', 'Screenshots the preview', 'Prints a postcard with QR', 'Mails it to their door', 'Tracks scans & replies'] },
  { id: 'car', short: 'Car', name: 'Car Redesign Agent', tag: 'Inventory, reimagined!',
    blurb: 'For dealerships — turns stock listings into cinematic reels and queues the outreach.',
    steps: ['Ingests dealer inventory', 'Qualifies premium trims', 'Renders a cinematic reel', 'Adds caption + CTA', 'Queues dealer outreach', 'Logs delivery status'] },

  // ── more agents ──
  { id: 'lawn', short: 'Lawn', name: 'Lawn Agent', tag: 'Lawns, revived!',
    blurb: 'For lawn care — finds high-value homes with the worst lawns and mails the after photo.',
    steps: ['Scans target neighbourhoods daily', 'Fetches satellite imagery', 'Grades lawn health with Gemini', 'Ranks the best prospects', 'Renders the lawn lush & green', 'Mails the owner a postcard'] },
  { id: 'heatmapper', short: 'Heat Mapper', name: 'Heat Mapper Agent', tag: 'Backyards, shaded!',
    blurb: 'For pergola & shade installers — qualifies backyards from the sky.',
    steps: ['Pulls recently sold homes', 'Grabs satellite & street imagery', 'Inspects each backyard with vision', 'Keeps patios with no shade cover', 'Adds sun hours & local forecast', 'Writes print-ready postcard copy'] },
  { id: 'review', short: 'Review', name: 'Review Agent', tag: 'Reviews, earned!',
    blurb: 'For reputation agencies — pitches low-review shops with a photo of their own storefront.',
    steps: ['Scans Google for low-review shops', 'Filters for owner-run storefronts', 'Pulls storefront & owner details', 'Ranks the shop most worth pitching', 'Renders the owner out front', 'Mails a QR postcard by name'] },
  { id: 'menu3d', short: '3D Menu', name: '3D Menu Agent', tag: 'Dishes, in 3D!',
    blurb: 'For restaurant marketers — turns reviewer food photos into an interactive 3D menu.',
    steps: ['Scans a city’s restaurants', 'Samples brand colours from photos', 'Converts dish photos to 3D models', 'Builds a live 3D menu + QR', 'Writes the pitch with Claude', 'Mails the postcard via PostGrid'] },
  { id: 'tender', short: 'Tender', name: 'Tender Agent', tag: 'Tenders, caught!',
    blurb: 'For bid teams — only the winnable tenders, the moment they publish.',
    steps: ['Monitors tender portals 24/7', 'Filters to your exact regions', 'Isolates your niche keywords', 'Reads documents for eligibility', 'Drafts the response to Sheets', 'Routes winnable bids to CRM or SMS'] },
  { id: 'finance', short: 'Finance', name: 'Finance Agent Package', tag: 'Invoices, handled!',
    blurb: 'For finance ops — invoices in, approvals routed, reminders out.',
    steps: ['Reads invoice emails', 'Extracts vendor, amount, tax, due date', 'Logs everything to Google Sheets', 'Checks duplicates & payment details', 'Routes bills for approval', 'Sends polite payment reminders'] },
  { id: 'solar', short: 'Solar', name: 'Solar Agent', tag: 'Roofs, solarised!',
    blurb: 'For commercial roofers & solar teams — a personalised roof + solar proposal per building.',
    steps: ['Scans commercial roofs by satellite', 'Scores age, condition, urgency', 'Estimates solar capacity', 'Identifies the real decision-maker', 'Calculates tax credit & savings', 'Generates proposal · starts outreach'] },
  { id: 'runway', short: 'RunwayScout', name: 'RunwayScout', tag: 'Racks, to reels!',
    blurb: 'For content studios — turns a clothing store’s own products into a fashion reel.',
    steps: ['Scans Google Maps for clothing stores', 'Filters for real inventory', 'Collects product images', 'Picks the best item to promote', 'Generates a 9:16 model reel', 'Mails the owner a QR postcard'] },
  { id: 'voltfinder', short: 'VoltFinder', name: 'VoltFinder Agent', tag: 'Chargers, placed!',
    blurb: 'For EV installers — finds car parks with no chargers and mails the ROI.',
    steps: ['Pulls commercial properties', 'Checks EV-charger directories', 'Captures each lot by satellite', 'Counts spaces & charger capacity', 'Calculates credits, rebates, payback', 'Renders before/after · mails postcard'] },
  { id: 'poolscout', short: 'PoolScout', name: 'PoolScout Agent', tag: 'Backyards, imagined!',
    blurb: 'For pool builders & landscapers — shows new owners the pool in their actual backyard.',
    steps: ['Finds newly sold homes', 'Filters by price, lot, location', 'Pulls the real backyard image', 'Generates a pool design + video', 'Estimates cost & value uplift', 'Mails the owner a QR postcard'] },
  { id: 'menureel', short: 'MenuReel', name: 'MenuReel AI', tag: 'Dishes, to reels!',
    blurb: 'For food marketers — turns a reviewer’s dish photo into a cinematic reel.',
    steps: ['Scrapes local restaurants', 'Flags weak photos, samples palette', 'Generates a 9:16 dish reel', 'Creates hosted link + QR', 'Writes the pitch with Claude', 'Mails the postcard · logs to Sheets'] },
  { id: 'voicedesk', short: 'VoiceDesk', name: 'VoiceDesk AI Receptionist', tag: 'Calls, answered!',
    blurb: 'For clinics & front desks — answers every call, books the appointment, 24/7.',
    steps: ['Answers every call instantly', 'Understands the caller’s intent', 'Answers FAQs in a natural voice', 'Books the appointment', 'Logs the call & outcome', 'Escalates what needs a human'] },
];
